#!/usr/bin/env bash
# Prints FizzBuzz from 1 to 100, separated by spaces.
out=""
for i in $(seq 1 100); do
	if [ $((i % 15)) -eq 0 ]; then
		token="FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		token="Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		token="Buzz"
	else
		token="$i"
	fi
	if [ -z "$out" ]; then
		out="$token"
	else
		out="$out $token"
	fi
done
echo "$out"
