#!/usr/bin/env bash
# Loops 1..10 using a while loop: 4 -> bad luck, 8 -> good luck, else Best School.
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
